Document: inspireme
Title: Debian inspireme Manual
Author: <insert document author here>
Abstract: This manual describes what inspireme is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inspireme/inspireme.sgml.gz

Format: postscript
Files: /usr/share/doc/inspireme/inspireme.ps.gz

Format: text
Files: /usr/share/doc/inspireme/inspireme.text.gz

Format: HTML
Index: /usr/share/doc/inspireme/html/index.html
Files: /usr/share/doc/inspireme/html/*.html
